
@host =  http://localhost:6000/api/notes
###
GET {{host}}/a508f95ca78b460cfb3923/wwe

### add new 
POST {{host}}/
Content-Type: application/json

{
  "content":"best pppppp 33333",
  "date":"2022-06-06",
  "important": true
} 
